### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by dogeow** [slippersheepig/chatgpt-html#14]
<img width="818" alt="image" src="https://user-images.githubusercontent.com/7204604/220851576-834bb2e9-14bb-4be0-8a70-2d609bfe27cb.png">

**Comment by slippersheepig** [comment]
用的人太多，我的账号临时超出OPENAI请求限制了，过一会就会恢复（没有具体时间）

**Comment by yaojiaogegehe** [comment]
大佬，能请教一下我按照你的自述文件操作，最后搭建出来的网站也没能响应是什么原因啊？

**Comment by yaojiaogegehe** [comment]
大佬，能请教一下我按照你的自述文件操作，最后搭建出来的网站也没能响应是什么原因啊？

**Comment by yaojiaogegehe** [comment]
> 用的人太多，我的账号临时超出OPENAI请申请限制了，过一次就会恢复（没有具体时间）

大佬，能请教一下我按照你的自述文件操作，最后搭建出来的网站也没能响应是什么原因啊？

**Comment by slippersheepig** [comment]
> > 用的人太多，我的账号临时超出OPENAI请申请限制了，过一次就会恢复（没有具体时间）
> 
> 大佬，能请教一下我按照你的自述文件操作，最后搭建出来的网站也没能响应是什么原因啊？

开新issue，贴上日志看看
