### ISSUE TITLE
macos 操作执行不成功

### ISSUE THREAD

**Issue by chunpat** [slippersheepig/chatgpt-html#16]
➜  chatgpt-html git:(proxy) ✗ sudo docker-compose up
htmchat is up-to-date
Attaching to htmchat
htmchat    | [2023-02-25 13:20:18 +0000] [1] [INFO] Starting gunicorn 20.1.0
htmchat    | [2023-02-25 13:20:18 +0000] [1] [INFO] Listening at: http://0.0.0.0:8088 (1)
htmchat    | [2023-02-25 13:20:18 +0000] [1] [INFO] Using worker: gevent
htmchat    | [2023-02-25 13:20:18 +0000] [7] [INFO] Booting worker with pid: 7
htmchat    | [2023-02-25 13:20:23 +0000] [7] [ERROR] Exception in worker process
htmchat    | Traceback (most recent call last):
htmchat    |   File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
htmchat    |     worker.init_process()
htmchat    |   File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
htmchat    |     super().init_process()
htmchat    |   File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
htmchat    |     self.load_wsgi()
htmchat    |   File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
htmchat    |     self.wsgi = self.app.wsgi()

**Comment by slippersheepig** [comment]
后面应该还有个具体的error信息的，日志没发全吧。个人猜测没创建config.json或者这个文件里面填写的内容有问题

**Comment by chunpat** [comment]
config.json
```
{
        "email": "cherellebop30a@hotmail.comxxxx",
        "password": "xxxxx"
}
```
错误信息
```
htmchat    | [2023-02-25 13:20:32 +0000] [7] [INFO] Worker exiting (pid: 7)
htmchat    | [2023-02-25 13:20:32 +0000] [1] [INFO] Shutting down: Master
htmchat    | [2023-02-25 13:20:32 +0000] [1] [INFO] Reason: Worker failed to boot.
htmchat    | [2023-02-25 13:20:33 +0000] [1] [INFO] Starting gunicorn 20.1.0
htmchat    | [2023-02-25 13:20:33 +0000] [1] [INFO] Listening at: http://0.0.0.0:8088 (1)
htmchat    | [2023-02-25 13:20:33 +0000] [1] [INFO] Using worker: gevent
htmchat    | [2023-02-25 13:20:33 +0000] [7] [INFO] Booting worker with pid: 7
htmchat    | [2023-02-25 13:20:39 +0000] [7] [ERROR] Exception in worker process
htmchat    | Traceback (most recent call last):
htmchat    |   File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
htmchat    |     worker.init_process()
htmchat    |   File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
htmchat    |     super().init_process()
htmchat    |   File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
htmchat    |     self.load_wsgi()
htmchat    |   File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
htmchat    |     self.wsgi = self.app.wsgi()
htmchat    |                 ^^^^^^^^^^^^^^^
htmchat    |   File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
htmchat    |     self.callable = self.load()
htmchat    |                     ^^^^^^^^^^^
htmchat    |   File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
htmchat    |     return self.load_wsgiapp()
htmchat    |            ^^^^^^^^^^^^^^^^^^^
htmchat    |   File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
htmchat    |     return util.import_app(self.app_uri)
htmchat    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
htmchat    |   File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/util.py", line 359, in import_app
htmchat    |     mod = importlib.import_module(module)
htmchat    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
htmchat    |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
htmchat    |     return _bootstrap._gcd_import(name[level:], package, level)
htmchat    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
htmchat    |   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
htmchat    |   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
htmchat    |   File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
htmchat    |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
htmchat    |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
htmchat    |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
htmchat    |   File "/chatgpt-html/main.py", line 11, in <module>
htmchat    |     chatbot = Chatbot(config)
htmchat    |               ^^^^^^^^^^^^^^^
htmchat    |   File "/home/appuser/.local/lib/python3.11/site-packages/revChatGPT/V1.py", line 40, in wrapper
htmchat    |     out = func(*args, **kwargs)
htmchat    |           ^^^^^^^^^^^^^^^^^^^^^
htmchat    |   File "/home/appuser/.local/lib/python3.11/site-packages/revChatGPT/V1.py", line 121, in __init__
htmchat    |     raise error
htmchat    |   File "/home/appuser/.local/lib/python3.11/site-packages/revChatGPT/V1.py", line 119, in __init__
htmchat    |     self.__login()
htmchat    |   File "/home/appuser/.local/lib/python3.11/site-packages/revChatGPT/V1.py", line 40, in wrapper
htmchat    |     out = func(*args, **kwargs)
htmchat    |           ^^^^^^^^^^^^^^^^^^^^^
htmchat    |   File "/home/appuser/.local/lib/python3.11/site-packages/revChatGPT/V1.py", line 160, in __login
htmchat    |     auth.begin()
htmchat    |   File "/home/appuser/.local/lib/python3.11/site-packages/OpenAIAuth.py", line 76, in begin
htmchat    |     self.__part_one(token=csrf_token)
htmchat    |   File "/home/appuser/.local/lib/python3.11/site-packages/OpenAIAuth.py", line 117, in __part_one
htmchat    |     self.__part_two(url=url)
htmchat    |   File "/home/appuser/.local/lib/python3.11/site-packages/OpenAIAuth.py", line 146, in __part_two
htmchat    |     self.__part_three(state=state)
htmchat    |   File "/home/appuser/.local/lib/python3.11/site-packages/OpenAIAuth.py", line 170, in __part_three
htmchat    |     self.__part_four(state=state)
htmchat    |   File "/home/appuser/.local/lib/python3.11/site-packages/OpenAIAuth.py", line 208, in __part_four
htmchat    |     self.__part_five(state=state)
htmchat    |   File "/home/appuser/.local/lib/python3.11/site-packages/OpenAIAuth.py", line 245, in __part_five
htmchat    |     self.__part_six(old_state=state, new_state=new_state)
htmchat    |   File "/home/appuser/.local/lib/python3.11/site-packages/OpenAIAuth.py", line 271, in __part_six
htmchat    |     self.__part_seven(redirect_url=redirect_url, previous_url=url)
htmchat    |   File "/home/appuser/.local/lib/python3.11/site-packages/OpenAIAuth.py", line 300, in __part_seven
htmchat    |     raise Error(
htmchat    | OpenAIAuth.Error

```


我看应该是没代理，认证错误了，明早我试试

**Comment by chunpat** [comment]
> config.json
> 
> ```
> {
>         "email": "cherellebop30a@hotmail.comxxxx",
>         "password": "xxxxx"
> }
> ```
> 
> 错误信息
> 
> ```
> htmchat    | [2023-02-25 13:20:32 +0000] [7] [INFO] Worker exiting (pid: 7)
> htmchat    | [2023-02-25 13:20:32 +0000] [1] [INFO] Shutting down: Master
> htmchat    | [2023-02-25 13:20:32 +0000] [1] [INFO] Reason: Worker failed to boot.
> htmchat    | [2023-02-25 13:20:33 +0000] [1] [INFO] Starting gunicorn 20.1.0
> htmchat    | [2023-02-25 13:20:33 +0000] [1] [INFO] Listening at: http://0.0.0.0:8088 (1)
> htmchat    | [2023-02-25 13:20:33 +0000] [1] [INFO] Using worker: gevent
> htmchat    | [2023-02-25 13:20:33 +0000] [7] [INFO] Booting worker with pid: 7
> htmchat    | [2023-02-25 13:20:39 +0000] [7] [ERROR] Exception in worker process
> htmchat    | Traceback (most recent call last):
> htmchat    |   File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
> htmchat    |     worker.init_process()
> htmchat    |   File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
> htmchat    |     super().init_process()
> htmchat    |   File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
> htmchat    |     self.load_wsgi()
> htmchat    |   File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
> htmchat    |     self.wsgi = self.app.wsgi()
> htmchat    |                 ^^^^^^^^^^^^^^^
> htmchat    |   File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
> htmchat    |     self.callable = self.load()
> htmchat    |                     ^^^^^^^^^^^
> htmchat    |   File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
> htmchat    |     return self.load_wsgiapp()
> htmchat    |            ^^^^^^^^^^^^^^^^^^^
> htmchat    |   File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
> htmchat    |     return util.import_app(self.app_uri)
> htmchat    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> htmchat    |   File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/util.py", line 359, in import_app
> htmchat    |     mod = importlib.import_module(module)
> htmchat    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> htmchat    |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
> htmchat    |     return _bootstrap._gcd_import(name[level:], package, level)
> htmchat    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> htmchat    |   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
> htmchat    |   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
> htmchat    |   File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
> htmchat    |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
> htmchat    |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
> htmchat    |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
> htmchat    |   File "/chatgpt-html/main.py", line 11, in <module>
> htmchat    |     chatbot = Chatbot(config)
> htmchat    |               ^^^^^^^^^^^^^^^
> htmchat    |   File "/home/appuser/.local/lib/python3.11/site-packages/revChatGPT/V1.py", line 40, in wrapper
> htmchat    |     out = func(*args, **kwargs)
> htmchat    |           ^^^^^^^^^^^^^^^^^^^^^
> htmchat    |   File "/home/appuser/.local/lib/python3.11/site-packages/revChatGPT/V1.py", line 121, in __init__
> htmchat    |     raise error
> htmchat    |   File "/home/appuser/.local/lib/python3.11/site-packages/revChatGPT/V1.py", line 119, in __init__
> htmchat    |     self.__login()
> htmchat    |   File "/home/appuser/.local/lib/python3.11/site-packages/revChatGPT/V1.py", line 40, in wrapper
> htmchat    |     out = func(*args, **kwargs)
> htmchat    |           ^^^^^^^^^^^^^^^^^^^^^
> htmchat    |   File "/home/appuser/.local/lib/python3.11/site-packages/revChatGPT/V1.py", line 160, in __login
> htmchat    |     auth.begin()
> htmchat    |   File "/home/appuser/.local/lib/python3.11/site-packages/OpenAIAuth.py", line 76, in begin
> htmchat    |     self.__part_one(token=csrf_token)
> htmchat    |   File "/home/appuser/.local/lib/python3.11/site-packages/OpenAIAuth.py", line 117, in __part_one
> htmchat    |     self.__part_two(url=url)
> htmchat    |   File "/home/appuser/.local/lib/python3.11/site-packages/OpenAIAuth.py", line 146, in __part_two
> htmchat    |     self.__part_three(state=state)
> htmchat    |   File "/home/appuser/.local/lib/python3.11/site-packages/OpenAIAuth.py", line 170, in __part_three
> htmchat    |     self.__part_four(state=state)
> htmchat    |   File "/home/appuser/.local/lib/python3.11/site-packages/OpenAIAuth.py", line 208, in __part_four
> htmchat    |     self.__part_five(state=state)
> htmchat    |   File "/home/appuser/.local/lib/python3.11/site-packages/OpenAIAuth.py", line 245, in __part_five
> htmchat    |     self.__part_six(old_state=state, new_state=new_state)
> htmchat    |   File "/home/appuser/.local/lib/python3.11/site-packages/OpenAIAuth.py", line 271, in __part_six
> htmchat    |     self.__part_seven(redirect_url=redirect_url, previous_url=url)
> htmchat    |   File "/home/appuser/.local/lib/python3.11/site-packages/OpenAIAuth.py", line 300, in __part_seven
> htmchat    |     raise Error(
> htmchat    | OpenAIAuth.Error
> ```
> 
> 我看应该是没代理，认证错误了，明早我试试

ok了，需要代理。

![](https://img.zzhpeng.cn/%E6%88%AA%E5%B1%8F2023-02-27%20%E4%B8%8A%E5%8D%8810.17.50.png)
