### ISSUE TITLE
建议改进2个地方

### ISSUE THREAD

**Issue by wingeva1986** [slippersheepig/chatgpt-html#17]
1.问题请求接口改为post。get方法有字数限制，贴段长代码就报错了。
2.聊天会话没有做隔离，多人使用对话上下文会干扰。没有会话重置按钮。

**Comment by slippersheepig** [comment]
> 1.问题请求接口改为post。get方法有字数限制，贴段长代码就报错了。
> 2.聊天会话没有做隔离，多人使用对话上下文会干扰。没有会话重置按钮。
#### 感谢反馈
* 经测试，ChatGPT官方网页版也有长度限制（作者github也有[说明](https://github.com/acheong08/ChatGPT/discussions/649)），将gunicorn默认的长度限制放开即可解决（目前已处理完毕）；
* 关于会话隔离问题，在作者github有多个issue及discussion提及，目前不确定是作者代码问题还是我的代码问题，但是如果是我这边的问题的话，恕我无力解决（不擅长），如果可以，欢迎提交pr，重置同理。

**Comment by wingeva1986** [comment]
> > 1.问题请求接口改为post。get方法有字数限制，贴段长代码就报错了。
> > 2.聊天会话没有做隔离，多人使用对话上下文会干扰。没有会话重置按钮。
> 
> #### 感谢反馈
> * 经测试，ChatGPT官方网页版也有长度限制（作者github也有[说明](https://github.com/acheong08/ChatGPT/discussions/649)），将gunicorn默认的长度限制放开即可解决（目前已处理完毕）；
> * 关于会话隔离问题，在作者github有多个issue及discussion提及，目前不确定是作者代码问题还是我的代码问题，但是如果是我这边的问题的话，恕我无力解决（不擅长），如果可以，欢迎提交pr，重置同理。

我没测试，但看文档，应该是chatbot

> > 1.问题请求接口改为post。get方法有字数限制，贴段长代码就报错了。
> > 2.聊天会话没有做隔离，多人使用对话上下文会干扰。没有会话重置按钮。
> 
> #### 感谢反馈
> * 经测试，ChatGPT官方网页版也有长度限制（作者github也有[说明](https://github.com/acheong08/ChatGPT/discussions/649)），将gunicorn默认的长度限制放开即可解决（目前已处理完毕）；
> * 关于会话隔离问题，在作者github有多个issue及discussion提及，目前不确定是作者代码问题还是我的代码问题，但是如果是我这边的问题的话，恕我无力解决（不擅长），如果可以，欢迎提交pr，重置同理。

我没测试，但粗看了下接口说明，应该是以UUID标识一个会话的，ask方法就可以传进去。

https://github.com/acheong08/ChatGPT/wiki/V1

**Comment by slippersheepig** [comment]
* 当发送超长字符给ChatGPT时，官方网页返回“The message you submitted was too long, please reload the conversation and submit something shorter.”自建网页则直接长时间无响应（作者代码没做这种抛出返回，也有可能openai本身就没作为抛出；因为现在没有在gunicorn做长度限制，准备加一行红字提示）
![1](https://user-images.githubusercontent.com/58287293/221822100-a42c3b1f-d536-4546-aefb-fcfd04283a35.png)
![1 1](https://user-images.githubusercontent.com/58287293/221822133-a2f1466b-90ce-4038-8d1f-0349808d138b.png)
* 经过一下午观察，发现既不是完全集中在一个会话，也不是每个新会话都会新建一个新聊天窗口，不准备处理这个问题了
![2](https://user-images.githubusercontent.com/58287293/221823048-f9f526b3-fea9-472c-a411-58b4c98eb8b6.png)
