### ISSUE TITLE
网页无响应

### ISSUE THREAD

**Issue by yaojiaogegehe** [slippersheepig/chatgpt-html#19]
按照readme的步骤来进行配置，以下是我docker-compose.yml和config.json的相关配置，在config.json我是用邮箱账号登录的。
[
![2](https://user-images.githubusercontent.com/115441764/222062270-15dc5518-6ec6-4803-b677-36b0e7b448a7.png)
![3](https://user-images.githubusercontent.com/115441764/222062281-4a09791a-a348-43e5-a8d5-78e9d923fc05.png)

](url)
最后docker命令也启用了，结果提问后却是未响应，如下图
![1](https://user-images.githubusercontent.com/115441764/222062712-30b05395-24fb-4362-abd2-9150b7fa19c8.png)
@slippersheepig

**Comment by slippersheepig** [comment]
config.json文件不支持注释，里面没用到的字段（包括说明）全部删掉

**Comment by slippersheepig** [comment]
#18 检查一下是否改过代码文件，http路径要对应。另外如果是在win上修改的文件，保存时注意格式要正确

**Comment by slippersheepig** [comment]
since there's no response for a while, close now
