### ISSUE TITLE
显示后端正在处理之后 直接报错了

### ISSUE THREAD

**Issue by TaoYeNa** [slippersheepig/chatgpt-html#2]

**Comment by slippersheepig** [comment]
目前api有问题，等待修复
refer [#608](https://github.com/acheong08/ChatGPT/issues/608)

**Comment by realzsy** [comment]
> 目前api有问题，等待修复
> refer [#608](https://github.com/acheong08/ChatGPT/issues/608)

官方api有问题吗？

**Comment by slippersheepig** [comment]
> > 目前api有问题，等待修复
> > refer [#608](https://github.com/acheong08/ChatGPT/issues/608)
> 
> 官方api有问题吗？

官方暂未公布api，这个项目用的api是以前官方用过的，模型编号泄露了，但是现在不能用了

**Comment by mboyka** [comment]
怪不得刚刚搭建提交后出错

**Comment by slippersheepig** [comment]
暂无官方API泄露或发布，此项目暂停维护，如有需要，请使用浏览器模拟登录版本
