### ISSUE TITLE
完整的api封装请参考这个项目

### ISSUE THREAD

**Issue by wingeva1986** [slippersheepig/chatgpt-html#23]
https://github.com/ojdev/chatgpt-webapi
正确的会话处理逻辑应该如此

**Comment by wingeva1986** [comment]
https://github.com/ojdev/chatgpt-webapi/releases/tag/v1.1.0
这里提到了会话没有隔离的原因

**Comment by slippersheepig** [comment]
清空会话虽然可以避免使用别人的会话问题，但是会产生另一个新问题，别人的会话可能会被突然中断，没法关联上下文连续对话。他的处理办法只是清空，并不是创建新会话，不是优雅的处理办法。
当然，为什么没有采用创建新会话这个处理方法，应该是因为有技术问题在里面，暂时没有很好的方式处理，[star最多的反代项目](https://github.com/acheong08/ChatGPT)作者有提到将来可能重构代码，暂时先观望吧。

**Comment by wingeva1986** [comment]
> 清空会话虽然可以避免使用别人的会话问题，但是会产生另一个新问题，别人的会话可能会被突然中断，没法关联上下文连续对话。他的处理办法只是清空，并不是创建新会话，不是优雅的处理办法。 当然，为什么没有采用创建新会话这个处理方法，应该是因为有技术问题在里面，暂时没有很好的方式处理，[star最多的反代项目](https://github.com/acheong08/ChatGPT)作者有提到将来可能重构代码，暂时先观望吧。

你都不看代码。。。他虽说“清空”，其实是首次提问重置会话ID，并没有删除。重置会话ID并不会影响其他用户使用，因为其他用户在他首次提问后，在前端已经拿到了属于他本次会话的id（当然你现在的前端没有这么做），他继续用就行，不影响

**Comment by wingeva1986** [comment]
> 清空会话虽然可以避免使用别人的会话问题，但是会产生另一个新问题，别人的会话可能会被突然中断，没法关联上下文连续对话。他的处理办法只是清空，并不是创建新会话，不是优雅的处理办法。 当然，为什么没有采用创建新会话这个处理方法，应该是因为有技术问题在里面，暂时没有很好的方式处理，[star最多的反代项目](https://github.com/acheong08/ChatGPT)作者有提到将来可能重构代码，暂时先观望吧。

你都不看代码。。。他虽说“清空”，其实是首次提问重置会话ID（同时返回一个新的会话id），避免传入空参数时被最近一次会话影响，而并没有删除某一个会话。重置会话ID并不会影响其他用户使用，因为其他用户首次提问后，在前端已经拿到了属于他本次会话的id（当然你现在的前端没有这么做），会话还在，他继续拿这个id去提问就行，不影响。
