### ISSUE TITLE
能否问问，需要多少安装空间？

### ISSUE THREAD

**Issue by ydqsbfsyi** [slippersheepig/chatgpt-html#28]
我在服务器上尝试安装两次，都不够空间，大概需要多少呢？

**Comment by slippersheepig** [comment]
按照[镜像](https://hub.docker.com/r/sheepgreen/chatgpt-html/tags)体积约3倍计算

**Comment by ydqsbfsyi** [comment]
> 按照[镜像](https://hub.docker.com/r/sheepgreen/chatgpt-html/tags)体积约3倍计算

谢谢帮助
