### ISSUE TITLE
The Compose file './docker-compose.yml' is invalid because: Unsupported config option for services: 'chatgpt'

### ISSUE THREAD

**Issue by xiwuqi** [slippersheepig/chatgpt-html#31]
在 CentOS 服务器上部署时出现的问题
![Snipaste_2023-03-15_12-05-29](https://cdn.staticaly.com/gh/xiwuqi/image-hosting@master/uPic/Snipaste_2023-03-15_12-05-29.png)
![image](https://user-images.githubusercontent.com/64734786/225204008-0b398ef2-857f-4cce-9710-ec013d973f8f.png)
docker-compose.yml 文件保留了原始配置，并没有做任何改动

**Comment by xiwuqi** [comment]
> 

![image-20230315121224330](https://cdn.staticaly.com/gh/xiwuqi/image-hosting@master/uPic/image-20230315121224330.png)
这是目录结构

**Comment by slippersheepig** [comment]
refer https://github.com/slippersheepig/chatgpt-web/issues/5#issuecomment-1436261442
