### ISSUE TITLE
CHATGPT_BASE_URL是什么

### ISSUE THREAD

**Issue by smallstrange** [slippersheepig/chatgpt-html#40]
不知道配成什么东西，配成域名提示404

**Comment by slippersheepig** [comment]
3种方法：
1.注释或删掉CHATGPT_BASE_URL这一行，使用作者的默认代理
2.CHATGPT_BASE_URL=https://ai.fakeopen.com/api/
这个是第三方的代理
3.以上都不行的话就自己搭代理，详见https://github.com/linweiyuan/go-chatgpt-api
自建代理若遇到问题请到作者github反馈

**Comment by smallstrange** [comment]
收到，谢谢
