### ISSUE TITLE
用腾讯云的海外服务器搭建了main分支里的网址，但在本地和服务器里都打不通，可能是什么原因？

### ISSUE THREAD

**Issue by Zoumachuan** [slippersheepig/chatgpt-html#6]
首先把防火墙的端口全部打开了，然后在本地git了main分支里的内容并上传到服务器里，cd chatgpt-html-main后把需要的文件都创建好了，只修改了端口号，运行docker-compose up -d后由于编码错误，我把main.py中的中文替换成了英文（是否和这步有关？），最后成功运行没有报错，但ip:端口不论在本地还是服务器上都time out，可能是什么原因呢？

**Comment by Zoumachuan** [comment]
端口本身应该没问题，不是特殊端口，在本地ping服务器只有100+ms

**Comment by Zoumachuan** [comment]
> 首先把防火墙的端口全部打开了，然后在本地git了main分支里的内容并上传到服务器里，cd chatgpt-html-main后把需要的文件都创建好了，只修改了端口号，运行docker-compose up -d后由于编码错误，我把main.py中的中文替换成了英文（是否和这步有关？），最后成功运行没有报错，但ip:端口不论在本地还是服务器上都time out，可能是什么原因呢？

或者作者可以给个联系方式吗？QQ1721292263

**Comment by slippersheepig** [comment]
是在win环境编辑的文件吗，注意保存为utf8无bom格式。原作者代码里没有写错误抛出，所以看起来没报错实际上可能是有的，我看看有时间补一下吧

不方便留

**Comment by Zoumachuan** [comment]
> 

在Ubuntu里编辑后没有报错，但还是打不通端口，请问是需要先安装什么依赖吗？

**Comment by slippersheepig** [comment]
项目代码本身应该是没什么问题的，我没用过腾讯云服务器，防火墙是不是要同时在网页版后台和服务器iptables打开才行

**Comment by Zoumachuan** [comment]
> 项目代码本身应该是没什么问题的，我没用过腾讯云服务器，防火墙是不是要同时在网页版后台和服务器iptables打开才行

还是不行，iptables全部放行之后依旧打不通，我决定还是暂时先用web版本吧，万分感谢

**Comment by slippersheepig** [comment]
due to the author didn't update chatgpt.unofficial so far, close this issue, if necessary I'll reopen
