### ISSUE TITLE
CHATGPT_BASE_URL是怎么样一个格式

### ISSUE THREAD

**Issue by fightroad** [slippersheepig/chatgpt-html#7]
CHATGPT_BASE_URL=你的代理服务端地址（不填默认使用作者服务器，目前偶尔会不可用）
这个地方是可以自己部署一个
[ChatGPT-Proxy](https://github.com/acheong08/ChatGPT-Proxy) 这个项目，然后填写自己的服务器地址吗？
如果是 那变量是怎么样一个格式？

**Comment by slippersheepig** [comment]
目前已知可用的是V2版代理，你发的那个项目已经不再维护了，不清楚还能不能用，你可以尝试下。
格式是http://ip:port/
注意最后的/不能省略
直接填这个地址，不需要引号

**Comment by slippersheepig** [comment]
due to this project was archived, close this issue
