### ISSUE TITLE
docker状态一直重启  看log有个keyerror 然后就关闭了 怎么解决

### ISSUE THREAD

**Issue by hty2012** [slippersheepig/chatgpt-html#8]
File \"/usr/local/lib/python3.11/site-packages/OpenAIAuth/OpenAIAuth.py\", line 352, in get_access_token\n","stream":"stderr","time":"2023-02-17T03:25:00.121560866Z"}
{"log":"    self.access_token = response.json()[\"accessToken\"]\n","stream":"stderr","time":"2023-02-17T03:25:00.121564987Z"}
{"log":"                        ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\n","stream":"stderr","time":"2023-02-17T03:25:00.121569417Z"}
{"log":"KeyError: 'accessToken'\n","stream":"stderr","time":"2023-02-17T03:25:00.121573633Z"}

**Comment by slippersheepig** [comment]
config.json没有账号配置，推荐填邮箱和密码，token随时过期（但是如果你是谷歌或者微软账号那就只能用token）

**Comment by slippersheepig** [comment]
如果有其他问题，请参考[这个项目](https://github.com/acheong08/ChatGPT)的issue
