### ISSUE TITLE
docker服务起不来

### ISSUE THREAD

**Issue by taoshanting** [slippersheepig/chatgpt-html#9]
把项目上传到服务器后，执行docker-compose命令后报错，信息如图片：
![MVIMG_20230218_142938](https://user-images.githubusercontent.com/35159740/219845101-01b0e65b-1220-48b2-84d7-fec7fc847686.jpg)

**Comment by slippersheepig** [comment]
缺少chat.html文件，创建一个，或者docker-compose.yml的volumes里删掉chat.html映射用镜像默认的

**Comment by taoshanting** [comment]
创建了chat.html文件后，服务可以起来了，但是一会就又关闭了，查看日志报错信息如下：
![MVIMG_20230218_172432](https://user-images.githubusercontent.com/35159740/219852710-72790bec-b613-42f5-970e-1d2b4b8767a8.jpg)
![MVIMG_20230218_172405](https://user-images.githubusercontent.com/35159740/219852714-7a914adb-6983-4e62-a099-8d0c17d94a4e.jpg)
![MVIMG_20230218_171957](https://user-images.githubusercontent.com/35159740/219852718-57a05cb5-13e8-4094-a8d1-140f06a2ad6e.jpg)

**Comment by slippersheepig** [comment]
refer #8

**Comment by taoshanting** [comment]
可是config.json里的账号已经配置了，是注册成功的邮箱和密码

**Comment by slippersheepig** [comment]
还有别的可能原因，[参考](https://github.com/acheong08/ChatGPT/issues/795)

**Comment by taoshanting** [comment]
想问下这种方式是不会消耗API调用次数的吗，但是需要连梯子才能访问。如果用API的方式调用是消耗调用次数，但是可以不用梯子就能访问？

**Comment by slippersheepig** [comment]
这个项目所有分支都不消耗openai api，如果你用proxy版也要梯子的话我也不清楚什么原因，但是跟api无关
另，调用openai api的前提是网络能连通openai

**Comment by taoshanting** [comment]
云终端是可以ping通的。我看原作者说可能是因为中国地区不能这样访问的原因，所以我打算把云实例换成国外的试试。

**Comment by taoshanting** [comment]
我想试试API分支，但是文档里说此分支已失效，还能继续用吗？
![1676725872183](https://user-images.githubusercontent.com/35159740/219867645-38bc1c2f-bb13-4a68-9aa2-5ea60e88ad74.jpg)

**Comment by slippersheepig** [comment]
不能，据说下周OpenAI会开放ChatGPT的API，视情况更新
